### ISSUE TITLE
Cannot create bolt. 

### ISSUE THREAD

**Issue by wingerbijay** [iDigitalFlame/ThunderStorm#2]
I am not able to create bolt. Following the quickstart guide to get started. 

python3 bin/jetstream -rc js.json -o bolt.exe windows/amd64 gives me following error 
![image](https://github.com/iDigitalFlame/ThunderStorm/assets/64668074/b55faa6a-9708-448a-8bb9-40549f2d276a)

**Comment by iDigitalFlame** [comment]
Hi, thanks for submitting an issue!

I see the root cause here, seems Golang's version changed some of the `const` strings we try to remove. Let me go through and update the search values for the latest version `go1.22`.

In the meantime, to get a build working, you can disable stripping by using the `--no-strip` command line argument.

Thanks!

**Comment by wingerbijay** [comment]
Hi, thank you for that. 

I tried with --no strip command, so here is the full command: python3 bin/jetstream -rc js.json -o bolt.exe windows/amd64 --no-strip

but I am still getting the same error. Here is the whole output. 
```
JetSteam Load complete!
- | Configured Options
============================================================
- | Target:               windows/amd64
- | Generator:            bolt
- |
- | Binary Configuration
- | = go:                 /usr/local/go/bin/go
- | = gcc:                /usr/bin/gcc
- | = upx:                /usr/bin/upx
- | = garble:             /root/go/bin/garble
- | = wgcc32:             /usr/bin/i686-w64-mingw32-gcc
- | = wgcc64:             /usr/bin/x86_64-w64-mingw32-gcc
- | = wres32:             /usr/bin/i686-w64-mingw32-windres
- | = wres64:             /usr/bin/x86_64-w64-mingw32-windres
- | = openssl:            /usr/bin/openssl
- | = osslsigncode:       /usr/bin/osslsigncode
- | Build Configuration
- | = Working Dir:        [temp directory]
- | = Linked Dir:
- | Build Modifications
- | = CGO:                True
- | = UPX:                False
- | = Crypt:              True
- | = Strip:              False
- | = Garble:             True
- | = Compact:            True
- | = GOROOT:
- | = GOPATH:
- | = Build Tags:         implant,nojson,noproxy
- | Support Configuration
- | = Manifest:           True
- | = CGO Export:         [randomized]
- | = CGO Secondary:      [randomized]
- | Signing Configuration
- | = Enabled:            True
- | = Sign Date:          Today
- | = Sign Variation:     712 days
- | = Spoof:              microsoft.com
- | = Spoof Name          Microsoft Windows
- | Resource Configuration
- | = Enabled:            True
- | = Icon:
- | = Title:
- | = Product:            Microsoft Windows Operating System
- | = Version:            [multi]
- | = Company:            Microsoft Corporation
- | = Filename:           [output filename]
- | = Copyright:          Microsoft Corporation. All rights reserved.
- | Bolt Generator
- | = Profile:            profile.bin
- | = Critical:           False
- | = Load:               True
- | = Pipe:               WindowMessageEvent
- | = Ignore:             False
- | = Linker:             Event
- | = Guardian:           WindowsLoginEvent
- | = Guard First:        False
- | = Service:            False
- | = CGO Thread:         [random]
- | = CGO Func:           [random]
05-21-12:40;46 [DEBUG] JetStream|MainThread: PRE: Made temp working directory "/tmp/jetstream-build-y223hrl5".
05-21-12:40;46 [DEBUG] JetStream|MainThread: PRE: Workspace built: {"os": "windows", "cgo": true, "dir": "/tmp/jetstream-build-y223hrl5", "out": "bolt.exe", "tags": [], "main": "", "arch": "amd64", "link": "", "flags": "", "export": "", "go_args": [], "gcc_args": [], "no_clean": false, "library": false, "main_cgo": "", "work_dir": "/tmp/jetstream-build-y223hrl5", "secondary": ""}
05-21-12:40;46 [INFO] JetStream|MainThread: SP1: Starting the Generate step..
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: Using Generator "bolt".
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: Generator "bolt" "run" returned "/tmp/jetstream-build-y223hrl5/bolt.go".
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: Preparing CGO entry files..
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: CGO entry point is "MhqvarMrOqIp".
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: Secondary CGO entrypoint found!
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: CGO secondary entry point is "wfXAjNLrEwZv".
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: Performing CGO entrypoint replacements on "/tmp/jetstream-build-y223hrl5/bolt.go".
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: Generator "bolt" "run_cgo" returned "/tmp/jetstream-build-y223hrl5/entry.c" and "bolt".
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP1: Completed the Generate step!
05-21-12:40;46 [INFO] JetStream|MainThread: SP2: Starting the Build step..
05-21-12:40;46 [DEBUG] JetStream|MainThread: SP2: Using GOROOT path "/usr/local/go".
05-21-12:40;46 [INFO] JetStream|MainThread: SP2: Building Compact GOROOT at "/tmp/jetstream-build-y223hrl5/root"..
05-21-12:40;48 [ERROR] JetStream|MainThread: Error during operation: /tmp/jetstream-build-y223hrl5/root/src/runtime/signal_windows.go: missing const msg = "runtime: signal received on thread not created by Go.\n" (/tmp/jetstream-build-y223hrl5/root/src/runtime/signal_windows.go: missing const msg = "runtime: signal received on thread not created by Go.\n")
Traceback (most recent call last):
  File "/home/winger/c2/ThunderStorm/bin/jetstream", line 849, in run
    o = self.build(d, workspace, r, f, output)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/winger/c2/ThunderStorm/bin/jetstream", line 336, in build
    tiny_root(r, c)
  File "/home/winger/c2/ThunderStorm/jetstream/include/builder.py", line 452, in tiny_root
    _sed(
  File "/home/winger/c2/ThunderStorm/jetstream/include/builder.py", line 729, in _sed
    raise ValueError(f"{path}: missing {old[x]}")
ValueError: /tmp/jetstream-build-y223hrl5/root/src/runtime/signal_windows.go: missing const msg = "runtime: signal received on thread not created by Go.\n"

05-21-12:40;48 [DEBUG] JetStream|MainThread: Removing working directory "/tmp/jetstream-build-y223hrl5".
Error: /tmp/jetstream-build-y223hrl5/root/src/runtime/signal_windows.go: missing const msg = "runtime: signal received on thread not created by Go.\n"!
```

note that i am running go version go1.22.3 linux/amd64

**Comment by iDigitalFlame** [comment]
Oop I'm sorry, not `--no-strip` it should be `--no-compact` thanks

**Comment by wingerbijay** [comment]
It worked. Thanks a heaps. Cheers.

**Comment by iDigitalFlame** [comment]
I just pushed a commit to fix the errors you were having, let me know if this fixes the errors. Thanks!

**Comment by wingerbijay** [comment]
Thank heaps. It works now.
